main: 'net.thundercode.block.BlockPlugin'
api-version: '1.13'
author: 'Osnixer'
name: 'trcBlock'
version: '1.0'

commands:
  block:
    description: 'It allows you to easily change items into blocks'
    aliases:
      - blocks
      - bloki
      - blok